[pytest]
minversion = "9.0"
addopts = ["-ra", "-q"]
testpaths = ["test"]

markers = [
    "module: module tests",
    "scenario: scenario tests",
    "collection: collection tests",
    "collector: collector tests",
    "filing: filing tests",
    "field: field tests",
    "core: core tests",
    "edger: EDGAR related tests",
    "edinet: EDINET related tests",
]

[tool.coverage.run]
source = ["src"]
branch = true
omit = ["*/__pycache__/*"]

[tool.coverage.report]
exclude_lines = [
    "pragma: no cover",
    "def __repr__",
    "raise AssertionError",
    "raise NotImplementedError",
    "if __name__ == .__main__.:",
    "if TYPE_CHECKING:",
]

