# generated by scripts/generate_filing_queries.py — do not edit

from fino_filing.filing.field import Field

class EDGARFilingQuery:
    """Generated query type for .q autocomplete."""
    cik: Field
    accession_number: Field
    company_name: Field
    form_type: Field
    filing_date: Field
    period_of_report: Field
    sic_code: Field
    state_of_incorporation: Field
    fiscal_year_end: Field
