# generated by scripts/generate_filing_queries.py — do not edit

from fino_filing.filing.field import Field


class EDINETFilingQuery:
    """Generated query type for .q autocomplete."""

    doc_id: Field
    edinet_code: Field
    sec_code: Field
    jcn: Field
    filer_name: Field
    ordinance_code: Field
    form_code: Field
    doc_type_code: Field
    doc_description: Field
    period_start: Field
    period_end: Field
    submit_datetime: Field
    parent_doc_id: Field
