#!/usr/bin/env python3
"""
Filing サブクラスから .q 補完用の Query クラスを生成する。

既存の Python クラス定義（Annotated[T, Field(...)]）をソースに、
*_queries.py を出力する。実行: python scripts/generate_filing_queries.py
"""

from __future__ import annotations

import ast
import sys
from pathlib import Path


def _is_filing_base(node: ast.expr) -> bool:
    """base が Filing かどうか（Name('Filing') または Attribute(..., 'Filing')）"""
    if isinstance(node, ast.Name):
        return node.id == "Filing"
    if isinstance(node, ast.Attribute):
        return node.attr == "Filing"
    return False


def _has_field_in_annotation(node: ast.expr) -> bool:
    """annotation が Annotated[..., Field(...), ...] の形かどうか"""
    if not isinstance(node, ast.Subscript):
        return False
    value = node.value
    if not isinstance(value, ast.Name) or value.id != "Annotated":
        return False
    slice_val = node.slice
    if isinstance(slice_val, ast.Tuple):
        elts = slice_val.elts
    elif isinstance(slice_val, (ast.Index, ast.expr)):  # Python 3.9+ slice は直接
        elts = [slice_val] if not isinstance(slice_val, ast.Tuple) else slice_val.elts
    else:
        elts = (
            getattr(slice_val, "elts", [slice_val])
            if hasattr(slice_val, "elts")
            else [slice_val]
        )
    if len(elts) < 2:
        return False
    for meta in elts[1:]:
        if isinstance(meta, ast.Call):
            func = meta.func
            if isinstance(func, ast.Name) and func.id == "Field":
                return True
            if isinstance(func, ast.Attribute) and func.attr == "Field":
                return True
    return False


def collect_filing_classes_and_fields(path: Path) -> list[tuple[str, list[str]]]:
    """
    1 つの .py ファイルをパースし、(クラス名, [Field 付き属性名のリスト]) のリストを返す。
    """
    text = path.read_text(encoding="utf-8")
    tree = ast.parse(text)
    result: list[tuple[str, list[str]]] = []

    for node in ast.walk(tree):
        if not isinstance(node, ast.ClassDef):
            continue
        bases = getattr(node, "bases", [])
        if not any(_is_filing_base(b) for b in bases):
            continue
        if node.name == "Filing":
            continue
        field_names: list[str] = []
        for item in node.body:
            if isinstance(item, ast.AnnAssign) and isinstance(item.target, ast.Name):
                name = item.target.id
                if name.startswith("_"):
                    continue
                if name in ("q", "source"):
                    continue
                if item.annotation and _has_field_in_annotation(item.annotation):
                    field_names.append(name)
        result.append((node.name, field_names))

    return result


def generate_queries_module(
    module_name: str,
    classes_with_fields: list[tuple[str, list[str]]],
) -> str:
    """1 モジュール分の Query クラス定義の Python ソースを生成する。"""
    lines = [
        "# generated by scripts/generate_filing_queries.py — do not edit",
        "",
        "from fino_filing.filing.field import Field",
        "",
    ]
    for class_name, field_names in classes_with_fields:
        if not field_names:
            continue
        lines.append(f"class {class_name}Query:")
        lines.append('    """Generated query type for .q autocomplete."""')
        for name in field_names:
            lines.append(f"    {name}: Field")
        lines.append("")
    return "\n".join(lines).rstrip()


def main() -> int:
    repo_root = Path(__file__).resolve().parent.parent
    src = repo_root / "src" / "fino_filing" / "filing"
    if not src.is_dir():
        print("fino_filing/filing not found", file=sys.stderr)
        return 1

    # 対象: filing_*.py のうち filing.py 以外
    for py_path in sorted(src.glob("filing_*.py")):
        if py_path.name == "filing.py":
            continue
        collected = collect_filing_classes_and_fields(py_path)
        if not collected:
            continue
        # 出力: filing_edger.py -> filing_edger_queries.py
        stem = py_path.stem
        out_path = src / f"{stem}_queries.py"
        content = generate_queries_module(stem, collected)
        out_path.write_text(content + "\n", encoding="utf-8")
        print(f"Generated {out_path}")

    return 0


if __name__ == "__main__":
    sys.exit(main())
