import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * 仕様（利用者向け）と開発（開発者向け）でサイドバーを分離する。
 */
const sidebars: SidebarsConfig = {
  specSidebar: ['intro', {type: 'autogenerated', dirName: 'spec'}],
  devSidebar: ['intro', {type: 'autogenerated', dirName: 'dev'}],
};

export default sidebars;
