import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Spec (users) and Dev (contributors) use separate sidebars.
 * "intro" is only in specSidebar so the displayed sidebar is unambiguous.
 */
const sidebars: SidebarsConfig = {
  specSidebar: ['intro', {type: 'autogenerated', dirName: 'spec'}],
  devSidebar: [{type: 'autogenerated', dirName: 'dev'}],
};

export default sidebars;
